# NumPy Tutorial

https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

In [3]:
import numpy as np

In [8]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
print(a.shape)
print(a.ndim)

(3, 5)
2


In [14]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [22]:
b = np.array([2,1,4], dtype=complex)
b

array([ 2.+0.j,  1.+0.j,  4.+0.j])

In [24]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [25]:
np.ones((5,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [26]:
np.empty((2,2))

array([[  0.00000000e+000,  -1.72723381e-077],
       [  9.88131292e-324,   2.78134232e-309]])

In [29]:
np.arange(0, 30, 5)

array([ 0,  5, 10, 15, 20, 25])

In [34]:
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [38]:
from numpy import pi
x = np.linspace(0, 2*pi, 10)
f = np.sin(x)
f

array([  0.00000000e+00,   6.42787610e-01,   9.84807753e-01,
         8.66025404e-01,   3.42020143e-01,  -3.42020143e-01,
        -8.66025404e-01,  -9.84807753e-01,  -6.42787610e-01,
        -2.44929360e-16])

In [54]:
A = np.array([[1,1], [1,0]])
print(A + A)
print(A - A)
print(A * A)
print(np.dot(A, A))

[[2 2]
 [2 0]]
[[0 0]
 [0 0]]
[[1 1]
 [1 0]]
[[2 1]
 [1 1]]


In [55]:
def f(x,y):
    return 10*x+y

In [57]:
b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [58]:
b[2,3]

23

In [62]:
b[0:5,3]

array([ 3, 13, 23, 33, 43])

In [61]:
b[:,3]

array([ 3, 13, 23, 33, 43])

In [67]:
b.view() # Shallow copy

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [66]:
b.copy() # Deep copy

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])